#! /bin/sh

sxhkd &
xrdb -load ~/.Xresources &
source ~/.bash_profile &
compton --backend glx -b &
urxvtd -q -o -f &
dunst &
$HOME/.fehbg &
$HOME/.config/polybar/polybar_launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          32
bspc config bottom_padding	    20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# user rules
bspc rule -a URxvt state=floating
bspc rule -a Google-chrome desktop='^2'
bspc rule -a discord desktop='^5'
bspc rule -a runelite.sh desktop='^6' state=floating
